#服务器配置
server:
  port: 80
  servlet:
    context-path: /analysis

#spring配置
spring:
  #页面路径
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/

  #热加载
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  #数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/analysis?useUnicode=true&characterEncoding=utf-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

#python配置
python:
    executor: D:\software\python\python.exe

#配置返回统一处理类
filter:
  class: analysis.controller.ApiController